# Generated by Django 5.0.6 on 2024-06-05 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=datetime.date(2024, 6, 5)),
            preserve_default=False,
        ),
    ]
