# Generated by Django 5.0.6 on 2024-06-11 20:03

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_creation_time_product_last_update_time'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('prodcuts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
